version: "3.8"
services:
    app:
        build:
            args:
                user: ubuntu
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: study
        container_name: app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./storage/logs:/var/www/storage/logs #will allow to write logs
        networks:
            - study-net

    db:
        image: mysql
        container_name: database
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - study-net

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/conf:/etc/nginx/conf.d/
            - ./docker-compose/nginx/ssl:/etc/nginx/ssl/
        networks:
            - study-net

volumes:
    db_data:
        driver: local

networks:
    study-net:
        driver: bridge
        external: true
